"""Seed data for the sample workspace ("Quillstack", a fictional B2B SaaS company).

The JSON files hold the hand-written parts of the sample: accounts, plans, recent activity and failed
payments. Everything numeric over time (daily MRR, flows, cohorts) is generated by the revenue model.
Loaders validate each file into typed, immutable records and cache the result.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from functools import cache
from importlib import resources
from typing import Any, Literal, cast

from churnwise.domain.types import Tone

CustomerStatus = Literal["Expanded", "Active", "At risk", "Past due", "Downgraded", "Churn scheduled"]
Trend = Literal["up", "flat", "down"]
ActivityKind = Literal["upgrade", "recovered", "cancellation", "seats", "downgrade", "new"]

_STATUSES: frozenset[str] = frozenset(
    {"Expanded", "Active", "At risk", "Past due", "Downgraded", "Churn scheduled"}
)
_TRENDS: frozenset[str] = frozenset({"up", "flat", "down"})
_ACTIVITY_KINDS: frozenset[str] = frozenset(
    {"upgrade", "recovered", "cancellation", "seats", "downgrade", "new"}
)
_TONES: frozenset[str] = frozenset({"brand", "brand_dark", "ink", "mint", "blue", "amber", "red", "starter"})


class FixtureError(ValueError):
    """A seed file is missing a field or holds a value outside its allowed set."""


def _choice(value: Any, allowed: frozenset[str], what: str) -> str:
    if value not in allowed:
        raise FixtureError(f"{what} {value!r} is not one of {sorted(allowed)}")
    return cast(str, value)


def _share_pair(value: Any, what: str) -> tuple[float, float]:
    if not (isinstance(value, list) and len(value) == 2 and all(0 <= float(v) <= 1 for v in value)):
        raise FixtureError(f"{what} must be a [start, end] pair of shares between 0 and 1")
    return float(value[0]), float(value[1])


def _ranked(value: Any, what: str) -> tuple[tuple[str, float], ...]:
    rows = tuple((str(label), float(share)) for label, share in value)
    if abs(sum(share for _, share in rows) - 100) > 0.5:
        raise FixtureError(f"{what} shares must add up to 100%")
    return rows


@cache
def _load(name: str) -> dict[str, Any]:
    text = resources.files(__package__).joinpath(name).read_text(encoding="utf-8")
    return cast(dict[str, Any], json.loads(text))


@dataclass(frozen=True, slots=True)
class PlanDefinition:
    name: str
    price: str
    tone: Tone
    #: Share of MRR at the start and the end of the model.
    mrr_share: tuple[float, float]
    customer_share: tuple[float, float]
    #: Monthly logo churn, in percent.
    churn: float


@dataclass(frozen=True, slots=True)
class Account:
    name: str
    plan: str
    mrr: float
    trend: Trend
    status: CustomerStatus
    health: int
    since: str
    owner: str


@dataclass(frozen=True, slots=True)
class ActivityItem:
    customer: str
    detail: str
    kind: ActivityKind
    #: Signed MRR effect of the event.
    amount: float
    when: str


@dataclass(frozen=True, slots=True)
class TimelineEntry:
    date: str
    title: str
    detail: str
    tone: Tone


@dataclass(frozen=True, slots=True)
class CustomerProfile:
    name: str
    plan: str
    status: CustomerStatus
    mrr: float
    lifetime_revenue: float
    health: int
    timeline: tuple[TimelineEntry, ...]


@dataclass(frozen=True, slots=True)
class OpenFailedPayment:
    customer: str
    amount: float
    decline_code: str
    attempts: int
    next_retry: str
    step: str


@cache
def plans() -> tuple[PlanDefinition, ...]:
    rows = []
    for raw in _load("plans.json")["plans"]:
        rows.append(
            PlanDefinition(
                name=raw["name"],
                price=raw["price"],
                tone=cast(Tone, _choice(raw["tone"], _TONES, "plan tone")),
                mrr_share=_share_pair(raw["mrrShare"], f"{raw['name']} mrrShare"),
                customer_share=_share_pair(raw["customerShare"], f"{raw['name']} customerShare"),
                churn=float(raw["churn"]),
            )
        )
    for edge in (0, 1):
        if abs(sum(p.mrr_share[edge] for p in rows) - 1) > 1e-9:
            raise FixtureError("plan MRR shares must add up to 1 at both ends of the model")
        if abs(sum(p.customer_share[edge] for p in rows) - 1) > 1e-9:
            raise FixtureError("plan customer shares must add up to 1 at both ends of the model")
    return tuple(rows)


@cache
def accounts() -> tuple[Account, ...]:
    return tuple(
        Account(
            name=raw["name"],
            plan=raw["plan"],
            mrr=float(raw["mrr"]),
            trend=cast(Trend, _choice(raw["trend"], _TRENDS, "trend")),
            status=cast(CustomerStatus, _choice(raw["status"], _STATUSES, "status")),
            health=int(raw["health"]),
            since=raw["since"],
            owner=raw["owner"],
        )
        for raw in _load("customers.json")["accounts"]
    )


@cache
def activity() -> tuple[ActivityItem, ...]:
    return tuple(
        ActivityItem(
            customer=raw["customer"],
            detail=raw["detail"],
            kind=cast(ActivityKind, _choice(raw["kind"], _ACTIVITY_KINDS, "activity kind")),
            amount=float(raw["amount"]),
            when=raw["when"],
        )
        for raw in _load("customers.json")["activity"]
    )


@cache
def profile() -> CustomerProfile:
    raw = _load("customers.json")["profile"]
    return CustomerProfile(
        name=raw["name"],
        plan=raw["plan"],
        status=cast(CustomerStatus, _choice(raw["status"], _STATUSES, "status")),
        mrr=float(raw["mrr"]),
        lifetime_revenue=float(raw["lifetimeRevenue"]),
        health=int(raw["health"]),
        timeline=tuple(
            TimelineEntry(
                date=e["date"],
                title=e["title"],
                detail=e["detail"],
                tone=cast(Tone, _choice(e["tone"], _TONES, "timeline tone")),
            )
            for e in raw["timeline"]
        ),
    )


@cache
def cancellation_reasons() -> tuple[tuple[str, float], ...]:
    return _ranked(_load("customers.json")["cancellationReasons"], "cancellation reason")


@cache
def decline_reasons() -> tuple[tuple[str, float], ...]:
    return _ranked(_load("recovery.json")["declineReasons"], "decline reason")


@cache
def open_failed_payments() -> tuple[OpenFailedPayment, ...]:
    return tuple(
        OpenFailedPayment(
            customer=raw["customer"],
            amount=float(raw["amount"]),
            decline_code=raw["declineCode"],
            attempts=int(raw["attempts"]),
            next_retry=raw["nextRetry"],
            step=raw["step"],
        )
        for raw in _load("recovery.json")["openFailed"]
    )
